### ISSUE TITLE
Expression pattern of type 'UnicodeScalar' cannot match values of type 'UnicodeScalar!'

### ISSUE THREAD

**Issue by iNoles** [tyrone-sudeium/JSONCore#13]
According to Xcode 8.1, there are 16 issues for this issues. 

it is relating to the all cases inside of

``` swift
switch scalar {
```

**Comment by tyrone-sportsbet** [comment]
I'll have this fixed by this weekend. Thanks for the report!

**Comment by tyrone-sudeium** [comment]
Sorry, wrong account!

Anyway yeah I'll look into this on the weekend.
