### ISSUE TITLE
Serialization performance

### ISSUE THREAD

**Issue by tyrone-sudeium** [tyrone-sudeium/JSONCore#5]
Tagging you in @VDKA !

Now that we've adopted an `indirect enum` I'm seeing some weird discrepancies with serialization performance.

`JSONSerializer` with `indirect enum` => 18 seconds
`JSONSerializer` with old enum => 5 seconds
New serializer with `indirect enum` => 10 seconds

I'm not entirely sure where the performance gap is coming from but we really need to find a way to bring this back down to the 5 second range. JSONCore is all about performance!

**Comment by tyrone-sudeium** [comment]
...and now with the added pretty printer support, we're down to 27 seconds. I suspect we're running into branch prediction misses on the CPU now; I can probably get it back to 10 seconds by duplicating the serialization code (once for pretty, once for not), but there's gotta be a way to structure this thing so that that's not necessary.

**Comment by vdka** [comment]
I just tried

``` swift
switch prettyPrint {
case false: return try compactJSONString()
case true: return try prettyJSONString()
}
```

Like you suggested, however, I didn't find any performance gains there.
Using indirect enums and a recursive function as the serializer was mostly to see if it could be done after [reading](http://colindrake.me/2015/10/28/implementing-a-small-dsl-in-swift/).
If you would rather we can put the old serializer back into place. It is 2x performance after all.

**Comment by tyrone-sudeium** [comment]
I'll probably restore the old code, but keep the indirect stuff in a branch, in case the Swift compiler ever improves the situation.
